### ISSUE TITLE
Problemas na inicialização do agatha

### ISSUE THREAD

**Issue by lucasjordinds** [lucasdiedrich/agatha#1]
Lucas, como vai?
Estou tentando instalar e inicializar o agatha para utilizar na iniciação científica da minha instituição e estou com alguns problemas. Como percebi que você é o cara mais indicado para isso resolvi tirar minhas dúvidas aqui.

Eu parei na parte do tutorial de instalação que manda eu criar uma pasta chamada app dentro da /agatha/docker/spring e então vem um codigo doido que não entendi se é para mover o app.jar e o aplication.yml para a pasta app ou se é pra renomear o app.jar. O detalhe é que esse app.jar não existe na minha pasta e por isso não consegui executar mais nada apartir daí.

Gostaria, por favor que me auxiliasse a utilizar o agatha usando o seu método.
Eu ficaria extremamente grato com a sua ajuda.
Utilizo o Arch Linux x86_64

**Comment by lucasjordinds** [comment]
@lucasdiedrich  mas uma vez venho aqui para tirar um dúvida. Depois que eu ativei o container usando os comandos:
docker run --name agatha \
           -p 8080:80 -p 8443:443 \
           -e ECIDADAO_SERVER=... \
           -v /etc/localtime:/etc/localtime \
           -d lucasdiedrich/agatha

Aparece o seguinte na linha de comando:

b84361fc7d4af3134cdf9f8ed98ac9ae7ef5eea7f60aee186f52d53376b80872

Como faço para acessar a interface do Agatha?

**Comment by lucasdiedrich** [comment]
@lucasjordinds, como você iniciou fazendo o bind em duas portas 8080 e 8443 você pode acessar diretamente no IP do container utilizando estas portas, ou IP da suas estação http//:localhost:8080/.

[Este artigo](http://tidahora.com.br/conhecendo-o-docker-parte-1/) também demonstra bem como utilizar e acessar as portas do container.

Qualquer dúvida estou a disposição.

**Comment by lucasjordinds** [comment]
Cara, muito obrigado mesmo pela instrução, estou muito agradecido por ter finalmente conseguido.
Mas eu tenho mais algumas dúvidas; a primeira é em relação ao comando descrito na sua wiki para criar usuário admin no docker hub que é a seguinte:

> docker exec -it <nome_do_container> create-admin 'Nome do usuário' 'CPF00000000000' 'meuemail@gmail.com'**
Quando eu executo esse comando com as devidas alterações retorna um erro:
bash: docker: No such file or directory

A outra dúvida que tenho é que ao entrar no agatha aparece que não estou autenticado então eu clico em autenticar e vou para outra página que retorna um erro de "502 Bad Gateway
nginx" eu dei as devidas permissões ao nginx então não sei do que se trata esse erro.

**Comment by eduardoengcomp** [comment]
Prezados, boa noite!

@lucasdiedrich Cara, primeiro muito obrigado pela disponibilização do app no [https://hub.docker.com/r/lucasdiedrich/agatha/](url)

Como indicado no passo-a-passo, executei o comando com as seguintes configurações:

docker run --name agatha \
           -p 8080:80 -p 8443:443 \
           -e ECIDADAO_SERVER=homologa-agatha.ufpr.br \
           -v /etc/localtime:/etc/localtime \
           -d lucasdiedrich/agatha

Antes disso, havia configurado os 3 arquivos da pasta /agatha/docker/spring como você indicou ao @lucasjordinds , seguindo os modelos deste link ([https://github.com/lucasdiedrich/agatha/tree/master/files/config](url)), substituindo o  client-id e client-secret pelas chaves que recebi no email e susbtituindo DOMINIO por homologa-agatha.ufpr.br.

Quando eu faço isso e acesso a aplicação usando o endereço IP-INTERNO-SERVIDOR:8080, ele me mostra a tela inicial do Agatha, conforme imagem anexa:
![agatha-tela-inicial-ok](https://user-images.githubusercontent.com/6821471/44497049-90fd1d80-a64d-11e8-9bde-3bb3e08f7b6e.png)

Quando eu clico pra autenticar, dai encontro o mesmo problema do @lucasjordinds, conforme imagem anexa: ![agatha-tela-autenticacao-nok](https://user-images.githubusercontent.com/6821471/44497108-d1f53200-a64d-11e8-9895-9090ef2a06db.png)

Se eu tento acessar direto pela URL (http://homologa-agatha.ufpr.br), ele não navega nem até a página inicial.

Tenho algumas duvidas (desculpa a n00bisse):

- A execução do "docker-compose up" substitui aquele comando "docker run --name agatha \ [continua...]" ou deve ser executado depois dele? Quando eu executo depois, ele não cria o container agatha (imagino que porque ele já tenha sido criado anteriormente) e cria apenas o agathadb. Nesse caso, quando eu tento criar um usuário, ele me mostra a mensagem abaixo:
![criacao-usuario](https://user-images.githubusercontent.com/6821471/44497296-e259dc80-a64e-11e8-9f05-bc2429ca30d4.png)

- Se, por outro lado, eu crio direto com o "docker-compose up"  sem exeutar o "docker run --name agatha \ [continua...]" antes, ele fica travado nessa tela meio que em um loop de INFO success, INDO spawned e INFO exited
![docker-compose-up](https://user-images.githubusercontent.com/6821471/44497487-f0f4c380-a64f-11e8-8aaa-8889496b07bc.png)

Estou fazendo alguma coisa de errado?

Agradeço muito pela ajuda dada até aqui.

Att,

Eduardo.

**Comment by lucasdiedrich** [comment]
@lucasjordinds, sobre o primeiro erro bash: docker: No such file or directory, o comando docker deve ser sempre executado com o usuário que o docker foi instalado, no caso ele não está encontrando o docker com o usuário que você está executando. Possivelmente foi instalado como root.

Sobre o 2º erro preciso que me anexe o arquivo de log do sistema, possivelmente o backend não foi inicializado por algum erro de configuração ou bug do próprio container.

Anexe os arquivos _/var/log/supervisord.log_, _/var/log/java.log_, _/var/log/nginx/error.log_
E também o retorno do comando abaixo:
```bash
docker exec -it agatha env
```

**Comment by eduardoengcomp** [comment]
@lucasdiedrich Obrigado pelos esclarecimentos

Em /var/log, não encontrei nenhum dos arquivos especificados
![var-log](https://user-images.githubusercontent.com/6821471/44530674-5e8f0700-a6c5-11e8-9944-26b86ba56546.png)

Mas executando o comando sugerido por você:
`docker exec -it agatha env`
Percebi que ele não tá carregando os parametros...
![docker-exec-it-agatha-env](https://user-images.githubusercontent.com/6821471/44530840-b6c60900-a6c5-11e8-819f-fcd765ad2cf3.png)

...Apesar de eu ter configurado o docker-compose conforme imagem abaixo:
![docker-compose](https://user-images.githubusercontent.com/6821471/44530812-a746c000-a6c5-11e8-9727-288d13053c0c.png)

Também não sei se ele usou o docker-compose.yml, porque eu primeiro executei o docker run e depois o docker-compose up

Vou tentar fazer uma instalação limpa executando apenas o docker-compose up.

**Comment by eduardoengcomp** [comment]
@lucasdiedrich 
Quando eu faço a instalação limpa pelo "docker-compose up" e utilizando o arquivo docker-compose conforme configurado no post anterior, ele aparentemente cria o banco com sucesso mas o agatha fica mostrando as mensagens abaixo em "loop" (já está há pelo menos 40 minutos assim). Isso é esperado?
![docker-compose-up-messages](https://user-images.githubusercontent.com/6821471/44534097-5e930500-a6cd-11e8-8ebd-0fa43c6e7318.png)

**Comment by lucasdiedrich** [comment]
@eduardoengcomp, realmente, se você executou o docker run antes do docker-compose e os dois comandos utilizam o mesmo nome como nome do container, neste caso agatha, ele não irá sobrescrever.

Os arquivos de log ficam em /var/log/ dentro do container, para ter acesso a ele basta executar o comando abaixo:
`bash
docker exec -it run agatha bash
`
De fato se as variáveis não estavam sendo carregadas a inicialização não era correta.

Sobre o loop, tente reiniciar o container com o comando docker restart agatha para ver se estabiliza.

**Comment by eduardoengcomp** [comment]
@lucasdiedrich 

Só pra ter dar o feedback e também ajudar os outros colegas de que as coisas estão bem encaminhadas agora.

1. Fiz a instalação limpa usando o docker-compose up, cofigurando o arquivo docker-compose.yml, ficando configurado como no modelo abaixo:
![docker-compose](https://user-images.githubusercontent.com/6821471/44584120-44652f80-a77e-11e8-9f6d-758afaa1514c.png)

2. Quando fiz isso, ele entra em um loop (conforme indiquei nesse post [aqui](https://github.com/lucasdiedrich/agatha/issues/1#issuecomment-415453244)).

3. Cancelei essa execução (Ctrl^C) e dei um **restart** no container, conforme o @lucasdiedrich  indicou [aqui](https://github.com/lucasdiedrich/agatha/issues/1#issuecomment-415477019)

4. Nesse momento a aplicação já estava acessível pelo navegador.

5. Executei novamente o comando `docker exec -it agatha env` e dessa vez ele retornou com os parâmetros configurados corretamente: 
![docker-exec-it-agatha-env](https://user-images.githubusercontent.com/6821471/44584325-ef75e900-a77e-11e8-80e3-9d16d419dc8b.png)

6. Executei o comando `docker exec -it agathadb bash` para acessar o bash do container (mais uma dica valiosa do @lucasdiedrich. Depois disso, tomei vergonha na cara e fui estudar melhor o funcionamento do Docker e as coisas de repente começaram a ficar mais claras haha)

7. A partir do bash do agatha, encontrei os arquivos de log
[error.log](https://github.com/lucasdiedrich/agatha/files/2318294/error.log)
[access.log](https://github.com/lucasdiedrich/agatha/files/2318295/access.log)
[supervisord.log](https://github.com/lucasdiedrich/agatha/files/2318296/supervisord.log)
[java.log](https://github.com/lucasdiedrich/agatha/files/2318297/java.log)

Identifiquei que o loop relatado nesse post [aqui](https://github.com/lucasdiedrich/agatha/issues/1#issuecomment-415453244) é registrado no supervisord.log

Percebi também que no error.log aparentemente eu não estou conseguindo acessar o banco. Talvez por isso quando eu carrego a pagina inicial, ele não traz os combos carregados e nem me mostra as opções do menu. Estou nesse ponto agora. Mas agora acho que consigo me virar. Paralelamente, tenho que configurar o DNS para que quando eu tentar fazer login, ele me redirecionar com o link que cadastramos lá no Planejamento.

@lucasdiedrich Mais uma vez muito obrigado por toda a ajuda!

**Comment by lucasdiedrich** [comment]
@eduardoengcomp , quase acertou na configuração do docker-compose, no docker-compose de exemplo existem todas as variáveis mas nem todas precisam ser utilizadas. No arquivo que você enviou você setou o DB_CHECK e CONF_CHECK para 0, sendo assim o script não verificará e não criará as devidas permissões no banco e nem no arquivo.yml

Somente comente as duas variáveis que indiquei acima e remova e inicie o container novamente, acredito que funcionará.

Acredito que o loop se deve justamente pelo Spring não estar conseguindo se conectar ao banco para criar as tabelas.

Obrigado.

**Comment by eduardoengcomp** [comment]
@lucasdiedrich Obrigado pelo retorno

1. Removi os containers e as imagens antigas;
2. Configurei o docker-compose novamente comentando os atributos DB_CHECK e CONF_CHECK;
![docker-compose-2](https://user-images.githubusercontent.com/6821471/44590655-0d991480-a792-11e8-80eb-59f38108d2c1.png)
3. Executei o `docker-compose up`, ele baixou novamente as imagens e fez a instalação (ver item 6)
4. Agora o `docker exec -it agatha env` retorna sem os os atributos DB_CHECK e CONF_CHECK;
![docker-exec-it-agatha-env](https://user-images.githubusercontent.com/6821471/44590813-6e285180-a792-11e8-847a-2a10de231299.png)
5. Mesmo assim, parece que o banco nao foi criado.
![banco-2](https://user-images.githubusercontent.com/6821471/44590880-94e68800-a792-11e8-8b64-3171d9205668.png)
[error.log](https://github.com/lucasdiedrich/agatha/files/2318801/error.log)
6. Na inicialização, durante a execução do `docker-compose up`, novamente tive que cancelar pq ele aparentemente ficou travado. O erro aparece no supervisord.log
[supervisord.log](https://github.com/lucasdiedrich/agatha/files/2318795/supervisord.log)
7. Fiz um restart e consigo acessar a aplicação, mas aparentemente ainda sem conseguir conectar no banco.
[error.log](https://github.com/lucasdiedrich/agatha/files/2318804/error.log)


Na container agathadb tem algum script que eu consigo executar para criação do banco (tabelas, grants, etc...)?

**Comment by lucasdiedrich** [comment]
@eduardoengcomp, vamos lá, a criação do banco em si é realizado pelo [contêiner do PostgreSQL](https://hub.docker.com/_/postgres/), ele automaticamente cria o banco **agatha** e somente isso.

O contêiner do agatha é quem deve criar os [schemas faltantes no script](https://github.com/lucasdiedrich/agatha/blob/master/files/usr/bin/pre-init#L12) quando iniciado, e a aplicação Spring cria as tabelas quando iniciado também.

Existe a possibilidade de o container do agatha não estar "visualizando" o container do banco, execute a linha a seguir de dentro do container agatha e posta o retorna por favor:
`bash
ping agathadb
`
Se ele não conseguir pingar é uma falha no network entre os containers, de qualquer maneira existe outro ponto para arrumar no docker-compose dai.

Obrigado.

**Comment by eduardoengcomp** [comment]
@lucasdiedrich 

Aparentemente o container do agatha está visualizando o container do banco:

![ping-agatha-db](https://user-images.githubusercontent.com/6821471/44679150-873e3600-aa10-11e8-8cfd-2758fcc7d550.png)

**Comment by eduardoengcomp** [comment]
Quando eu tento executar o pre-init (não sei se poderia executa-lo "sozinho" ou se ele deve ser executado dentro de alguma sequencia de inicialização), ele me retorna o seguinte erro:

![pre-init](https://user-images.githubusercontent.com/6821471/44681252-81e3ea00-aa16-11e8-83c5-d2d84c63c7d2.png)

**Comment by lucasdiedrich** [comment]
Para visualizar as tabelas no banco tem que usar o comando, SELECT * FROM pg_catalog.pg_tables;
Como eles estão em outro schema e não no public as tabelas não aparecem com o comando \dt

Porém acredito que encontramos o problema, um dos 3 arquivos de configuração está faltando, o application.properties. Verifique se este arquivo existe dentro da pasta /config pois eles deveria.

**Comment by lucasdiedrich** [comment]
@eduardoengcomp, sem os arquivos a aplicação Java não inicia e o Spring não cria as tabelas, eu acredito que anteriormente havia dito que, ### OU, usa as variaveis de ambiente, OU você usa seus arquivos de configuração. Na inicialização do contêiner comenta a linha que você está montando a pasta /config.

Desculpa porque só agora que eu subi lá nos prints e vi que no docker-compose estava marcado para montar o volume /, comente a linha e recrie o container.

Agora vai.

**Comment by lucasdiedrich** [comment]
@eduardoengcomp esse erro aconteceu comigo uma única vez, execute a sql abaixo no banco de dados do agatha e reinicie a aplicação. Caso solucione colocarei a SQL no script de inicialização:

`sql
DELETE FROM DATABASECHANGELOGLOCK;
`

**Comment by eduardoengcomp** [comment]
Oi @lucasdiedrich 

Executei o comando conforme sugerido:

![databasechangelock-deleted](https://user-images.githubusercontent.com/6821471/44993526-46df3a80-af71-11e8-97e2-1e64ef7b4507.png)

Depois, iniciei novamente os containeres. Na nova inicialização, fica travado como mostrado na imagem abaixo. Então inicio novamente separadamente com o comando start:

![restart](https://user-images.githubusercontent.com/6821471/44993586-8148d780-af71-11e8-8c01-ec804e6004a3.png)

Dessa forma, como vc pode ver [aqui](https://homologa-agatha.ufpr.br) ele ate inicia, mas nao me mostra o menu e nem carrega os combos quando eu acesso a página inicial (ele deveria carregar?). Pode ser que ele nao esteja inicializando o backend? Eu consigo em algum lugar ver a lista de comandos que ele executa durante a inicialização do backend?

Ia te perguntar sobre o link de autenticação, mas acabei de pegar a nova imagem e agora essa parte está funcionando (apesar de retornar pra mim o mesmo erro do colega do outro issue; vou verificar com o Brasil Cidadão se falta alguma liberação).

**Comment by lucasdiedrich** [comment]
O menu carrega somente após a autenticação @eduardoengcomp,
![image](https://user-images.githubusercontent.com/817482/44994668-1b128380-af76-11e8-9d49-5fd123ddfbd4.png)
Depois de autenticar:
![image](https://user-images.githubusercontent.com/817482/44994686-2f568080-af76-11e8-92db-31662bb08097.png)

Este erro aconteceu comigo, se não me engano foi problema no **grant** que eles fizeram, porque se não me engano este erro acontece no BrasilCidadão, não?

Qualquer coisa coloca um print para verificar, se for do lado do agatha o erro estará salvo nos arquivos de log. Vou encerrar esta issue, como o @lucasjordinds não participou mais. 

Se o problema acontecer qualquer outra tipo de erro que não foi tratado nesta thread abra uma nova issue.
