### ISSUE TITLE
Qual a versão dessa Build? Como atualizar para a 2.0? 

### ISSUE THREAD

**Issue by alexandremundim** [lucasdiedrich/agatha#11]

**Comment by lucasdiedrich** [comment]
@alexandremundim infelizmente após as últimas alterações realizadas no projeto agatha não foi mais possível realizar qualquer tipo de build do projeto. Você pode fazer o clone do projeto e realizar a build manualmente usando [este guia](https://docs.docker.com/engine/reference/commandline/build/).

**Comment by lucasdiedrich** [comment]
Infelizmente não há como atualizar esta build sem ser realizando a build manual.
