### ISSUE TITLE
Salvar dados externamente

### ISSUE THREAD

**Issue by marcelojorge** [lucasdiedrich/agatha#12]
No tutorial não está contemplado o salvamento dos dados do agatha externamente ao container. Como posso fazer isso de outra maneira que não um dump da base. Algum volume pode ser montado ?
O volume config é apenas para salvar informações de configuração da aplicação.

**Comment by lucasdiedrich** [comment]
@marcelojorge Acredito que os dados ficam salvos diretamente no banco de dados, do mais as dúvidas podem ser retiradas diretamente no projeto do agatha. Este projeto não está mais sofrendo atualizações devidos as última alterações da equipe....
