### ISSUE TITLE
Quando clico para logar sou redirecionado para o site do serpro

### ISSUE THREAD

**Issue by nerdseverino** [lucasdiedrich/agatha#18]
![Capturar](https://user-images.githubusercontent.com/23561457/86062798-deaff180-ba3f-11ea-9ad7-0d5e38e86f9a.PNG)

**Comment by nerdseverino** [comment]
Eu consigo subir os containers:
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                      NAMES
0738b8b0685a        lucasdiedrich/agatha   "/usr/bin/supervisor…"   7 minutes ago       Up 7 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   agatha
959bcde45ac0        postgres:11-alpine     "docker-entrypoint.s…"   2 hours ago         Up 2 hours          5432/tcp                                   agathadb

Segue o env do container:

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
HOSTNAME=0738b8b0685a
TERM=xterm
DB_HOST=agathadb
DB_PASSWORD=gestaoriscos
DB_USER=gestaoriscos
DB_NAME=agatha
DB_CHECK=1
CONF_CHECK=1
ECIDADAO_ENV=TESTE
ECIDADAO_SERVER=gestaoderiscos.ceee.local
ECIDADAO_ID=gestaoderiscos-ceee
ECIDADAO_SECRET=xxxxxxxxxxxx
SIORG=
affinity:container==71566c4387b1c6238cd84e6de1b1dd50de1e93014ae1ff5c1528ed601d4b8b47
LANG=C.UTF-8
JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
JAVA_VERSION=8u212
JAVA_ALPINE_VERSION=8.212.04-r0
JAVA_OPTS=-server -Xmx2G -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70
HOME=/root

Segue o application.yaml

[root@svAgatha agatha]# docker exec -it agatha cat /config/application.yaml
ecidadao:
  client-id: gestaoderiscos-ceee
  client-secret: xxxxxxxxxxxxxxxxxx
  pre-established-redirect-uri: https://gestaoderiscos.ceee.local/gestaoriscos/api/login/openid
  sistema:
    dominio: gestaoderiscos.ceee.local
    url-pattern-protegido: /**
    redireciona-login-sucesso: https://gestaoderiscos.ceee.local
    redireciona-logout-sucesso:  https://gestaoderiscos.ceee.local
  use-current-uri: false
  scope: openid
  # URIS dO AMBIENTE DE TESTES
  access-token-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/token
  user-authorization-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/authorize
  validacao-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/jwk

Quando eu clico no link para logar ele me redireciona para a página do Serpro:
https://www.serpro.gov.br/

Alguém pode me ajudar?

**Comment by lucasdiedrich** [comment]
@nerdseverino conseguiu resolver sua situação? Acredito que possa ser algo relacionado a uri de autorização, a mesma está identica a encaminhada a voce no email de autorização ?

Nossa instituição optou por não utilizar o sistema, mas verifiquei que também o mesmo não foi atualizado mais, acredito que vc terá que usar o [manual de instalação](https://softwarepublico.gov.br/social/agatha/manuais-de-usuario/manual-de-instalacao-v8-junho2019) para verificar se os arquivos dentro do container estão corretos.

Qualquer dúvida estou a disposição.

**Comment by LisandroGuerra** [comment]
@lucasdiedrich @nerdseverino o link do manual de instalação já não existe. Alguém aqui tem o manual? Preciso de uma ajuda para colocar isso de pé.

Obrigado

**Comment by lucasdiedrich** [comment]
Pelo o que eu entendi o software não é mais publico e se manteve a qualidade de quando foi lançado é melhor nem perder tempo tentando instalar.

Demorei algo de 1 semana para fazer esse container e o sistema foi descartado em 1 dia pela instituição, imagina agora sem a documentação publica.

Vou encerrar este projeto. Obrigado.
