### ISSUE TITLE
SSL lets encrypt - Agatha

### ISSUE THREAD

**Issue by christophergoncavles** [lucasdiedrich/agatha#19]
Prezados, estou com dificuldades em colocar certificado SSL lets encrypt no sistema Ágatha, algum dos senhores já conseguiram? Caso afirmativo possa me dar uma luz? Obrigado.

**Comment by lucasdiedrich** [comment]
Prezado, não tive problemas em hospedar a aplicação com qualquer tipo de certificado, porém pode ser que existem problemas ao se utilizar com o  Lets Encrypt. Infelizmente como a instituição escolheu por não utilizar mais esta aplicação não houve avanços no container.

Qualquer duvida utilize o site oficial do agatha: https://softwarepublico.gov.br/social/agatha
