### ISSUE TITLE
Não esta criando os schemas

### ISSUE THREAD

**Issue by carlsonsantana** [lucasdiedrich/agatha#2]
Ao rodar o docker eu pude perceber que o script de criação dos schemas do sistema e de auditoria não estão sendo executados, conforme pode ser visto na imagem em anexo.
![agatha1](https://user-images.githubusercontent.com/3837162/44492381-a9177180-a63a-11e8-85c6-e35da5b88026.png)

Eu pude resolver esse problema criando manualmente os schemas `gestaoriscos` e `aud_gestaoriscos`.

**Comment by lucasdiedrich** [comment]
Bom dia @carlsonsantana, a criação dos schemas é o primeiro item realizado na inicialização do container. [Pode ser visto aqui.](https://github.com/lucasdiedrich/agatha/blob/master/files/usr/bin/pre-init#L12).

Acredito que o usuário criado não foi dada a devida permissão de master no banco de dados, ou a verificação do banco foi desabilitada. 

Por favor, anexe o retorno do comando abaixo para verificarmos o arquivo de inicialização do docker (Não se esqueça de suprimir as chaves)

```bash
docker exec -it agatha env
```

Se possível também seu arquivo de docker-compose.

Obrigado.

**Comment by carlsonsantana** [comment]
De fato estava configurado para não executar a conferência com o banco de dados por padrão.
