### ISSUE TITLE
Falha no redirecionamento

### ISSUE THREAD

**Issue by carlsonsantana** [lucasdiedrich/agatha#3]
Mesmo alterando os parâmetros no arquivo do docker e no proprio application.yml o sistema não preenche os campos de ID e o DNS do sistema.
![agatha2](https://user-images.githubusercontent.com/3837162/44492531-3f4b9780-a63b-11e8-848c-9509838e299b.png)

**Comment by lucasdiedrich** [comment]
@carlsonsantana, bom dia, acredito que o container foi inicializado de maneira incorreta. o Client ali em sua URL está apontando para *ID*, essa keyword não é mencionada em qualquer lugar na construção do container.

Como foi inicializado o container? (Docker run / Docker compose)
Como está seu arquivo docker-compose (se foi utilizado)

Anexe o retorno do comando abaixo:
```bash
docker exec -it agatha env
```

**Comment by carlsonsantana** [comment]
Eu havia editado apenas o yml, editando a variável do dockerfile funcionou.
