### ISSUE TITLE
Erro no java ao instalar com docker-compose

### ISSUE THREAD

**Issue by sergiocharpineljr** [lucasdiedrich/agatha#5]
Boa tarde Lucas, tudo certo?

Estou tentando realizar a instalação do Agatha em um ambiente de testes com a imagem fornecida no seu repositório. Criei o arquivo docker-compose.yml  
[docker-compose.txt](https://github.com/lucasdiedrich/agatha/files/2329311/docker-compose.txt)
seguindo o exemplo e rodei o comando docker-compose up. Vários processos sobem porém o processo do java apresenta erro, conforme abaixo:

gathadb    | 2018-08-28 18:05:28.782 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
agathadb    | 2018-08-28 18:05:28.783 UTC [1] LOG:  listening on IPv6 address "::", port 5432
agathadb    | 2018-08-28 18:05:28.801 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
agathadb    | 2018-08-28 18:05:28.832 UTC [42] LOG:  database system was shut down at 2018-08-28 18:05:28 UTC
agatha      | 2018-08-28 15:05:28,836 INFO spawned: 'nginx' with pid 7
agatha      | 2018-08-28 15:05:28,839 INFO spawned: 'java' with pid 8
agathadb    | 2018-08-28 18:05:28.842 UTC [1] LOG:  database system is ready to accept connections
agatha      | 2018-08-28 15:05:28,898 INFO exited: java (exit status 1; not expected)
agatha      | 2018-08-28 15:05:29,901 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
agatha      | 2018-08-28 15:05:29,902 INFO spawned: 'java' with pid 11
agatha      | 2018-08-28 15:05:29,928 INFO exited: java (exit status 1; not expected)
agatha      | 2018-08-28 15:05:31,933 INFO spawned: 'java' with pid 13
agatha      | 2018-08-28 15:05:31,957 INFO exited: java (exit status 1; not expected)
agatha      | 2018-08-28 15:05:34,963 INFO spawned: 'java' with pid 15
agatha      | 2018-08-28 15:05:34,988 INFO exited: java (exit status 1; not expected)
agatha      | 2018-08-28 15:05:34,989 INFO gave up: java entered FATAL state, too many start retries too quickly

Rodando o pre-init na mão ocorre o seguinte erro:
bash-4.4# pre-init
Verificando banco de dados...
NOTICE:  schema "gestaoriscos" already exists, skipping
CREATE SCHEMA
NOTICE:  schema "aud_gestaoriscos" already exists, skipping
CREATE SCHEMA
ALTER ROLE
ERRO !!!
NÃO FOI POSSIVEL ENCONTRAR O ARQUIVO DE CONFIGURAÇÃO application.properties

Já solicitei as chaves para o Brasil Cidadão porém ainda não tive retorno e deixei os valores padrão do exemplo. Pode ter relação com o erro?

**Comment by lucasdiedrich** [comment]
@sergiocharpineljr , boa tarde, está acontecendo o mesmo erro que [expliquei aqui](https://github.com/lucasdiedrich/agatha/issues/1#issuecomment-416660019). Ou seja, você deve utilizar as variaveis de ambiente OU montar o /config, mas nunca o dois ao mesmo tempo. Comente a linha baixo: 
` # - "/volumes/agatha/config:/config"`

E depois crie o container novamente. Acredito que resolverá seu problema.

**Comment by sergiocharpineljr** [comment]
@lucasdiedrich Obrigado! Funcionou.
Como sugestão, acho válido colocar comentário no exemplo do seu docker-compose.yml

**Comment by lucasdiedrich** [comment]
Vou comentar, obrigado.
